# Ticks between hurting the entity.
# 20 ticks = 1 second.
ticks-per-damage: 20
# Amount of damage points to hurt.
# 1.0 = 1/2 of a heart.
# 10.5 = 5 and 1/4 hearts.
damage-amount: 3.0
# Entity config.
entities:
  # A list of entity types.
  # Find a full list at: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  types:
    - "ARMOR_STAND"
    - "ITEM_FRAME"
    - "PAINTING"
    - "VILLAGER"
    - "WANDERING_TRADER"
    - "WOLF"
    - "OCELOT"
    - "CAT"
    - "PARROT"
    - "LLAMA"
    - "TRADER_LLAMA"
    - "DONKEY"
    - "MULE"
    - "HORSE"
    - "SKELETON_HORSE"
    - "ZOMBIE_HORSE"
    - "ALLAY"
    - "MINECART"
    - "MINECART_CHEST"
    - "MINECART_FURNACE"
    - "MINECART_TNT"
    - "MINECART_HOPPER"
    - "MINECART_MOB_SPAWNER"
    - "MINECART_COMMAND"
    - "OAK_BOAT"
    - "SPRUCE_BOAT"
    - "BIRCH_BOAT"
    - "JUNGLE_BOAT"
    - "ACACIA_BOAT"
    - "DARK_OAK_BOAT"
    - "MANGROVE_BOAT"
    - "CHERRY_BOAT"
    - "BEE"
    - "PLAYER" # This is how you disable damage to players.
  # If the list above is a whitelist.
  # If this is false, then it is a blacklist.
  is-whitelist: false
# Worlds config.
worlds:
  # A list of world names.
  names:
    - "lobby"
  # If the list above is a whitelist.
  # If this is false, then it is a blacklist.
  is-whitelist: false