name: '${name}'
version: '${version}'
main: '${main}'
authors: [ Drak ]
depend:
  - BukkitOfUtils
description: A plugin to simply make it so that stone cutters damage entities.
website: https://site.plasmere.net
folia-supported: true

api-version: 1.21

commands:
  reloadstonedamager:
    description: Reload the config file.
    permission: stonedamager.commands.reloadcmd
    aliases:
      - rlsd
      - reloadsd