name: '${name}'
version: '${version}'
main: '${main}'
authors: [ Drak ]
depend:
  - BukkitOfUtils
description: A plugin to simply make it so that stone cutters damage entities.
website: https://site.plasmere.net
api-version: 1.14
folia-supported: true